select
stats.yt_channel_id as "YT Channel ID"
, stats.channel_title as "Channel Title"
, stats.video_title as "Video"
, stats.yt_video_id as "YT Video ID"
, stats.published_date as "Published Date"
, stats.month as "Month"
, stats.views as "Views (All Time)"
, lag(stats.views,-1) over (partition by stats.yt_video_id order by month desc) as "Previous Views (All Time)"
, stats.yt_likes as "Likes (All Time)"
, lag(stats.yt_likes,-1) over (partition by stats.yt_video_id order by month desc) as "Previous Likes (All Time)"
, stats.yt_dislikes as "Dislikes (All Time)"
, lag(stats.yt_dislikes,-1) over (partition by stats.yt_video_id order by month desc) as "Previous Dislikes (All Time)"
, stats.yt_comments as "Comments (All Time)"
, lag(stats.yt_comments,-1) over (partition by stats.yt_video_id order by month desc) as "Previous Comments (All Time)"
, pvp.pvp

from (select yt_channel_id
, channel_title
, video_title
, yt_video_id
, to_date(published_date) as published_date
, date_trunc('month',to_date(date)) as month
, ifnull(max(to_number(views)),0) as views
, ifnull(max(to_number(yt_likes)),0) as yt_likes
, ifnull(max(to_number(yt_dislikes)),0) as yt_dislikes
, ifnull(max(to_number(yt_comments)),0) as yt_comments
 from thresher.yt_video_stats_over_time
 where date >= '2018-10-01'
 and yt_channel_id in(
 'UC0SBn2zaskenN1hl_PCtQWw',
 'UCeO7Obz1NdrZYhI4PtstNuA',
 'UCqXXBpycrF0q8Q2NHIu5Y3A',
 'UCl1HONfXYsCI9ATs_ZNSQDQ'/*,
 'UCQmE9qgzRd2eGqJ1Z2ACl5A',
 'UCD6Y-S86lY_8NqriBjDP2Qw',
 'UCIfV-AOz4jZeazVDbzgT9lQ',
 'UClqUSY9SshvuFja6yNXp4nQ',
 'UCEYfsfyne69mFfNTcZeZ6gw',
 'UC9ZQYIa5fX_Pf75508JtPBg',
 'UCrniLr5HDebHfskhSSAAt0A',
 'UCcAT4ylQFMRuntX0B-ZRwtA',
 'UC33t-fSHCIFjvMUhWhJHX6g',
 'UC7hgDFSPvJVIUx_b8i1cILA',
 'UC_ntXHv-XdKCD7CPynVvnQw',
 'UCgVTP0yVURjY3Fnugvp7DCg',
 'UCvNBXWGykQrWb7kPAn5eLUQ',
 'UCvZHe-SP3xC7DdOk4Ri8QBw',
 'UCmajVTORW3vp5qM8r0myznA',
 'UCHSauBGVrjyfpWCjfNVvmng',
 'UC6CGQMMnnUwwjeK0ujkeF6Q',
 'UC6ZnM9vJ7OFVVvzOACDkfGg',
 'UCePE_9yUaBe478B_CuCBcoA',
 'UC3GriadTkHBnfgd2UFETGOA',
 'UCOU-IZLwstnFKxX3m3_P4fQ',
 'UCXwtJA8pO_Gf1HBZ0Hgyi2A',
 'UCHY2-UtRFv1WKf4o7cpEp3w',
 'UCxidp0WgNPBdIXpHZKQcoMw',
 'UC9YydG57epLqxA9cTzZXSeQ',
 'UCbLIqv9Puhyp9_ZjVtfOy7w',
 'UCOUh2z8YkidOzPLBXPMv33A',
 'UCPGuorlvarThSlwJpyTHOmQ',
 'UCW7h-1mymnJ96akzjrmiIgA',
 'UCuCtanBJXOPAEIAUXf9944g',
 'UCdyGT0Fe8deDAwqfHK3s5TA',
 'UCD1Em4q90ZUK2R5HKesszJg',
 'UC_F8DoJf9MZogEOU51TpTbQ',
 'UCL9wK9vQjmgyx7jGt20ZOkg',
 'UCEkorHXUNJ5tpcH0VE77_fA',
 'UCUYdOka3TBY0OV75AkiuMRw',
 'UCr0dIxUwa5uR8Wm5VZxVwnQ',
 'UCFiHjGyrJux8Rt4e6mUPU-w',
 'UCY4gAmuQf9JZpN0sEYOmaBg',
 'UC4zyoIAzmdsgpDZQfO1-lSA',
 'UCj4XSmDqIhRT4frKzRTMyrA',
 'UCvLZ2K_L7iaoyUQX1Hkjl0Q',
 'UCtfKuU7DNZgOSpRn1ksB6jw',
 'UCKMRqFNffptUiJyKGvvf6kg',
 'UC52XYgEExV9VG6Rt-6vnzVA',
 'UCs0ifCMCm1icqRbqhUINa0w',
 'UCSc6s-ZJXKlSQr51dsox34g',
 'UCxn8csYeZg6awRnZS-aqg0g',
 'UC8Mw2Mx1r1NgIRHPKmfIYlQ',
 'UCTQKT5QqO3h7y32G8VzuySQ',
 'UCQMxCuhm25CUS9MZKjZ2ihQ',
 'UCb1Fx7ZjON_6F29taDKEuSQ',
 'UCVz19v62F_lOImHxDM_rnsA',
 'UC_LtqnFEM3N3SZzc2qPk2pg',
 'UCoyaxd5LQSuP4ChkxK0pnZQ',
 'UCOsVSkmXD1tc6uiJ2hc0wYQ',
 'UCAhqshVw3AKUK4t8CFGA2gw',
 'UCPpddbTbOr_uWWQT9Pw1rbA',
 'UCK7CPGf74Fpes6kKLMuAdBg',
 'UCIHBybdoneVVpaQK7xMz1ww',
 'UCd1Xmm1TFBD-lfZUWaWf7EA',
 'UC5Qk8mWBwtMyEj7iQQYRk1A',
 'UCPq2ETz4aAGo2Z-8JisDPIA',
 'UCQCuF3-MPYBSu-l8Mf-PXsA',
 'UCFVnigSYgiQvRENXrAIh09g',
 'UCBUg2-Z74rDf8XhaYVon9bg',
 'UC2UKjt0-LKPQ7Nu2a2Q39Ag',
 'UCfhGCMntOdvnorxaMNCbDOg',
 'UCNdpD9V0PIrH1glUJ6RG4-w',
 'UCEa_Oh2Ut2G05AGue5QNUzA',
 'UCH3sMKVJ2P7hm7ROBy5FHJg',
 'UCpx2BZg8ABgaDV50sGJtWAg',
 'UCQSuIHSbDFH6Enz3AXeUHaA',
 'UCZfDHQE3mrZ7123Wl3iRhbg',
 'UCxo56gzJQ_fhb6svPqTSewg',
 'UCaLdl0827np4QVPESo794og',
 'UClG8odDC8TS6Zpqk9CGVQiQ',
 'UCCkxMbfZ80VFwwiRlIG5P5g',
 'UCxqFGyOvpJTITKGk0aF1GYA',
 'UCKkpgwjdJ-ohfG0YcqAt9Bw',
 'UCs9Bi1j5s25Yinhmd-NJvJw',
 'UCs9xWQlXpkHVoSrbdCPBwyQ',
 'UChDyKjO7PB_QuqTTFKKR9Iw',
 'UCSo0TqIHMNPOE-NZ2Dwmkpg',
 'UCeN_jCE20yurlNWyT6hrtRA',
 'UCbu2SsF-Or3Rsn3NxqODImw',
 'UCnZ7P-Tab_LqLQECgPlW-nw',
 'UCYLACCLDA1laE6u_-4aBrew',
 'UCUnRn1f78foyP26XGkRfWsA',
 'UCk2ipH2l8RvLG0dr-rsBiZw',
 'UCJx5KP-pCUmL9eZUv-mIcNw',
 'UC2Nn9kZr7KJHGqdt28-QZRw',
 'UC3E8iPQGBdAnOQR_cmkEbsw',
 'UCmeds0MLhjfkjD_5acPnFlQ',
 'UCNeU-ameY0dcKiltExqvhIw',
 'UCtnIt0RNn3UiaysQCE-8hHQ',
 'UCP_FgMqOxp_VsM0UfrL-DxA',
 'UC_-UccuRRj9_PfGZqaRzjWA',
 'UCwgmcpjC4rPqyOnE9nDlmBg',
 'UCKS8WtM7U144j4fAU4xqiCw',
 'UCbWdUfIDdki5LfY6j4et9PQ',
 'UC7NCg0venpKJg3kuJojKlbQ',
 'UCpVdq9gLew6E76BmfB2GJ0w',
 'UCmONQe9yHyPcETc5xdiZMcA',
 'UCZVeEavzrEZvLazxwKKTRiQ',
 'UCKy1dAqELo0zrOtPkf0eTMw',
 'UCedmzK8pHrU57erP9_oYNJg',
 'UC4LKeEyIBI7kyntQMFXTh0Q',
 'UCplLxaDjDeGuHtjAJuijfww',
 'UCM7EG1_z6zNJdjAYsyTuCyg',
 'UCg5idxxVnOx25-pYmeMhUCg',
 'UCFCLm6HxfrIH_NSRgqqbpAg',
 'UChIjW4BWKLqpojTrS_tX0mg',
 'UCyJEmM7DtB3XHH8VSnhj6XA',
 'UCy7Pjs6-k_NdHWTcRZLzWAg',
 'UCw_LCWreyWaFKRGBuORlaFw',
 'UCCyrXyelKeXFx5KDgldMmNw',
 'UCvGWdOpqf44AChMzqV9Ja5Q',
 'UCwkUBN7foWU9GcY5cFmso-Q',
 'UCmrw0M9fGg-lB2SS_kBpHsw',
 'UC2t5bjwHdUX4vM2g8TRDq5g',
 'UCh0spNBu88_0UVNbFcmZBag',
 'UChAjpm5hoadZ5kFCjJygHTw',
 'UCqi79K1X0lDePvDbZCJ2b5w',
 'UC_3cWMvKJdIqC5lxtAd3IQA',
 'UCvqRdlKsE5Q8mf8YXbdIJLw',
 'UCvqRdlKsE5Q8mf8YXbdIJLw',
 'UCBoKEaoksimOkpDOPPhyIUA',
 'UCKBjveweSxSyvKLutroLSGA',
 'UCbJ40sjcmYgCjGClftgBu7A',
 'UCzSItlUKaVNWbd7ybbfnFhg',
 'UC-AAk4vhWHPzR-cV4o5tLRg',
 'UC56rj_ydfr-iDOD7kw9gYPQ',
 'UCQthemUrkJnFZRRmGfTvyGA',
 'UCAEym5kVuaRjzFQdeE23K2w',
 'UC1sELGmy5jp5fQUugmuYlXQ',
 'UCMncR-XXNXhMyJELEgCrHlg',
 'UCKmLw-0rYN0prXDFITjN4og',
 'UCzQu9Zj8Dpj7gkQ53qDomyA',
 'UCSoc4XAihwzAA7p29tpAu9A',
 'UCYAJjqIukwm4r3GHEpJDhVw',
 'UCXXBi6rvC-u8VDZRD23F7tw',
 'UCGIY_O-8vW4rfX98KlMkvRg',
 '/UCG275E2gosKB-UPk-qCK8qw',
 'UC23CkkRDleBbvcwu_CcB3rA',
 'UCaXjGGAmLX-pn0Zv5wAYg9w',
 'UCdYTiTMkdQUFbWF6gbRwmZw',
 'UC4xyf_Z-pEQOTaRVyjXfA1g',
 'UCRcI9KjoUgCuBkgo306zWLw',
 'UCGbuAbSys-10iPfvxtkcTCQ',
 'UCssdZ293BU5UBeTerxh0oiw',
 'UCiAInBL9kUzz1XRxk66v-gw',
 'UCJoRdHp3Bd4dgSeYhQWmQfQ',
 'UCjzOFLm1ZqQBOf_MMb4UJ2Q',
 'UC1JOnWZrVWKzX3UMdpnvuMg',
 'UCgaPRP68bbyHnfkPhWWBrNw',
 'UCorkyFoPfQ6uZtl8vRyU1ew',
 'UCdThq5VFIm4HVZe5WnrIqvQ',
 'UCTu8uX6lp735Jyc9wbM8I3w',
 'UCz7S6LMS5Vb1UN_9xU37cNA',
 'UCgK_2VQWwigtTr_5TviGy2w',
 'UCnXDQbqIdp-HQuDyM4p12ng',
 'UClOf1XXinvZsy4wKPAkro2A',
 'UC-2Y8dQb0S6DtpxNgAKoJKA',
 'UCFctpiB_Hnlk3ejWfHqSm6Q',
 'UCmeeY9kzNswUpbYyJntb3Aw',
 'UCWKHac5bjhsUtSnMDFCT-7A',
 'UCJqdvIL9boKz6cXEdcx6V1w',
 'UCbyFV2lioP9a1YlUC4gm6xA',
 'UCM1xfX_G9oLhyb_TkTYjjaA',
 'UCmiCK8aqFP3Fx4-SHWKZLsA',
 'UCS6s3OidfTU0fMRScTGE_jg',
 'UCMI3Y-8q9BOpajXkN3DmFFg',
 'UCS2iGSouOopNHXFBcWtBQiA',
 'UCdKuPY64fEpI4cdlBSyvEJw',
 'UCdKuPY64fEpI4cdlBSyvEJw',
 'UC6VcWc1rAoWdBCM0JxrRQ3A',
 'UCzH3iADRIq1IJlIXjfNgTpA',
 'UCBIucJqzWm9H7Q0oxO7tfUQ',
 'UCWfXR0-F7MI-TbqikgEdJcQ',
 'UCEO8dgJ3sbCU0dgZ7Eir92g',
 'UCWj7XnnfbKHGVnZ8iSoETSQ',
 'UCI-Q7uYhRVMxyrmcZRf0Egg',
 'UCOV1dDjRSowkB1lXj4ZoeWQ',
 'UCA5SLTAVA6unn1M-6lbo1NA',
 'UCQKyy9Wl7hsVn1BP7BC53Yg',
 'UCTeLqJq1mXUX5WWoNXLmOIA',
 'UCZ2h0d4tP0R8klduwj-_bDQ',
 'UCBGBXQmTRZ0uwfxvcCMfz_A',
 'UC2WWBPpcENmF3CkHQx3UB2A',
 'UCUCMPd9b70oNX51guypaYhw',
 'UCf2PB4w6M3co9GxQKTOvQMA',
 'UCwVVpHQ2Cs9iGJfpdFngePQ',
 'UCXO2ZE-H4ZVjJDjTuQzv-Bw',
 'UC5BTcArAnit9p5W7etFsPsA',
 'UCLSWNf28X3mVTxTT3_nLCcw',
 'UC-pYdpQSasQvmocEDWZUotQ',
 'UCF0t9oIvSEc7vzSj8ZF1fbQ',
 'UCSCoziKHqjqbox3Fv3Pb4BA',
 'UCFXKLSrT-4-Mf5TRqv40rgw',
 'UCzybXLxv08IApdjdN0mJhEg',
 'UCpUu6hoAK8axMVZ2c_jgMCQ',
 'UC-LDrQRCxSifhrqNwldwZ-A',
 'UCugJq15BiB-c1NDYPHiznWQ',
 'UCFMvBfqGInJ22WynMV8Ohrw',
 'UC4Ndz98NI_-9VQM3E7fctnQ',
 'UCydtMNspoPAlqBjFSGnigSw',
 'UCBMvc6jvuTxH6TNo9ThpYjg',
 'UC2FB3JTommu79v-i2fi9_bA',
 'UCTqWN7lps75nnS07twBfVhw',
 'UCyL1mikIB37EjyWRzigjL9w',
 'UCg0FSqPeiGD_lIiPaaAehQg',
 'UCiCHOfMKGn1byQ1oq4kTPEw',
 'UCj1J3QuIftjOq9iv_rr7Egw',
 'UCI8aLCzjk8T0_49ZGYjYg9w',
 'UCLQd4upg6HQNjiXJYUJdxFw',
 'UCHqAOjD1bj-PvtPcK8qDFMQ',
 'UCLJ3dwvVPsudKCvNKsCFglA',
 'UC1h424KQY-jGGQe3inlqfiA',
 'UCbLj9QP9FAaHs_647QckGtg',
 'UC6tL95G3ZD_JLUrn52JM_7w',
 'UCAOfB5hs-T-CNeb1DCmqegg',
 'UCjBp_7RuDBUYbd1LegWEJ8g',
 'UCozZmz40Oc6NYD4JtZJgO8A',
 'UC_h2l2T4FrJzfdMF6RbOrcQ',
 'UC_kkVs4I84Bth70ZIeJCQow',
 'UCc8JKj5y6NVUd7RooLMvjdQ',
 'UC_WugflsmNelDMVhpOp2pdA'*/
)

group by 
 yt_channel_id
, channel_title
, video_title
, yt_video_id
, month
, published_date

) as stats

left join (select yt_channel_id , yt_video_id, paid_view_percentage as pvp from thresher.yt_video_stats) as pvp
on pvp.yt_video_id=stats.yt_video_id

limit 10